<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyTitle>TimelapseRTSP</AssemblyTitle>
    <Description>Creates timelapses from RTSP camera streams during imaging sessions</Description>
    <Authors>Jeremie Klein</Authors>
    <RootNamespace>NINA.Plugin.TimelapseRTSP</RootNamespace>
    <AssemblyName>NINA.Plugin.TimelapseRTSP</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NINA.Plugin" Version="3.2.0.9001" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="LibVLCSharp" Version="3.9.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>
      xcopy /Y /S "$(TargetDir)*.*" "$(LocalAppData)\NINA\Plugins\3.0.0\TimelapseRTSP\"
    </PostBuildEvent>
  </PropertyGroup>
</Project>
